package m_ddl_generator.dialect;

import m_ddl_generator.model.ColumnMetadata;
import m_ddl_generator.model.TableMetadata;
import java.util.ArrayList;
import java.util.List;

public class PostgreSqlDialect implements SqlDialect {

    @Override
    public List<String> createDropTableSql(TableMetadata table) {
        List<String> sqls = new ArrayList<>();
        sqls.add("DROP TABLE IF EXISTS " + table.getTableName() + " CASCADE;");
        return sqls;
    }

    @Override
    public String createTableDefinitionSql(TableMetadata table) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE TABLE IF NOT EXISTS ").append(table.getTableName()).append(" (\n");

        List<String> pkColumns = new ArrayList<>();
        List<String> definitions = new ArrayList<>();

        for (ColumnMetadata col : table.getColumns()) {
            if (col.isForeignKey()) continue; // FK 컬럼은 나중에 ALTER로 추가

            if (col.isPrimaryKey()) pkColumns.add(col.getName());
            definitions.add("            " + buildColumnSql(col));
        }

        sb.append(String.join(",\n", definitions));

        if (!pkColumns.isEmpty()) {
            sb.append(",\n            PRIMARY KEY (").append(String.join(", ", pkColumns)).append(")");
        }
        sb.append("\n        );");
        return sb.toString();
    }

    private String buildColumnSql(ColumnMetadata col) {
        StringBuilder sb = new StringBuilder();
        sb.append(col.getName()).append(" ").append(col.getDbType());

        if (!col.isNullable()) sb.append(" NOT NULL");

        // 🔥 [수정 포인트]
        if (col.isAutoIncrement()) {
            sb.append(" GENERATED BY DEFAULT AS IDENTITY");
        } else if (col.getDefaultValue() != null && !col.getDefaultValue().isEmpty()) {
            // 수정 전: sb.append(" DEFAULT ").append(col.getDefaultValue());
            // ❌ "DEFAULT DEFAULT 0" 이 되어버림

            // 수정 후: 그냥 값만 붙입니다. (값 자체에 이미 "DEFAULT"가 포함되어 있음)
            sb.append(" ").append(col.getDefaultValue());
        }

        return sb.toString();
    }

    @Override
    public List<String> createAlterTableSql(TableMetadata table, ColumnMetadata col) {
        List<String> sql = new ArrayList<>();
        if (col.isForeignKey()) {
            // 1. 컬럼 추가
            sql.add(String.format("ALTER TABLE %s ADD COLUMN %s BIGINT;", table.getTableName(), col.getName()));

            // 2. 제약조건 추가
            String constraintName = "fk_" + table.getTableName() + "_" + col.getName();
            sql.add(String.format("ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s;",
                    table.getTableName(), constraintName, col.getName(),
                    col.getFkTargetTable(), col.getFkTargetColumn(), col.getOnDeleteAction()));
        }
        return sql;
    }
}