package m_ddl_generator.dialect;

import dsl_variable.v2.MFieldType;
import m_ddl_generator.model.ColumnMetadata;
import m_ddl_generator.model.TableMetadata;
import utils.LogPrinter;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class PostgreSqlDialect implements SqlDialect {

    @Override
    public String getField(MFieldType fieldType) {

        if(fieldType.equals(MFieldType.UUID_V_7)) {
            return "UUID";
        } else if (fieldType.equals(MFieldType.JSON)) {
            return "JSONB";
        }

        return null;
    }

    @Override
    public List<String> createDropTableSql(TableMetadata table) {
        List<String> sqls = new ArrayList<>();
        // 세미콜론 제거 (빌더에서 처리)
        sqls.add("DROP TABLE IF EXISTS " + table.getTableName() + " CASCADE");
        return sqls;
    }

    @Override
    public String createTableDefinitionSql(TableMetadata table) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE TABLE IF NOT EXISTS ").append(table.getTableName()).append(" (\n");

        List<String> pkColumns = new ArrayList<>();
        List<String> definitions = new ArrayList<>();

        for (ColumnMetadata col : table.getColumns()) {
            if (col.isForeignKey()) continue;

            if (col.isContainPrimaryKey()) pkColumns.add(col.getName());

            // [수정] 공백 12개 -> 탭(\t) 하나로 변경 (XML 용량 감소 및 가독성 향상)
            definitions.add("\t" + buildColumnSql(col));
        }

        sb.append(String.join(",\n", definitions));

        if (!pkColumns.isEmpty()) {
            // [수정] 여기도 탭으로 변경
            sb.append(",\n\tPRIMARY KEY (").append(String.join(", ", pkColumns)).append(")");
        }

        // [수정] 세미콜론 제거
        sb.append("\n)");
        return sb.toString();
    }

    private String buildColumnSql(ColumnMetadata col) {
        StringBuilder sb = new StringBuilder();
        sb.append(col.getName()).append(" ").append(col.getType());

        if (!col.isContainNullable()) sb.append(" NOT NULL");

        if (col.isContainAutoIncrement()) {
            sb.append(" GENERATED BY DEFAULT AS IDENTITY");
        } else if (col.getDefaultValue() != null && !col.getDefaultValue().isEmpty()) {
            // 이미 값에 'DEFAULT'가 포함되어 있다고 가정하고 붙임
            sb.append(" ").append(col.getDefaultValue());
        }

        if(col.isContainUUIDV7()) {
            sb.append(" CONSTRAINT " + col.getName() + "_v7_chk CHECK (substring(id::text, 15, 1) = '7')");
        }

        return sb.toString();
    }

    @Override
    public List<String> createAlterTableSql(TableMetadata table, ColumnMetadata col, HashMap<String, List<String>> parentFieldTypes) {
        List<String> sql = new ArrayList<>();
        if (col.isForeignKey()) {


            String parentFieldType = parentFieldTypes.get(col.getFkTargetTable())
                    .stream()
                    .filter(type -> type != null && !type.isEmpty()
                    ).findFirst()
                    .orElseThrow(() -> new IllegalArgumentException("[PostgreSQLDialect] Index Parent Field Type is NULL"));



            // 세미콜론 제거
            sql.add(String.format("ALTER TABLE %s ADD COLUMN %s %s", table.getTableName(), col.getName(), parentFieldType));

            String constraintName = "fk_" + table.getTableName() + "_" + col.getName();
            sql.add(String.format("ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s",
                    table.getTableName(), constraintName, col.getName(),
                    col.getFkTargetTable(), col.getFkTargetColumn(), col.getOnDeleteAction()));
        }
        return sql;
    }

    @Override
    public String createAddColumnIfNotExistsSql(TableMetadata table, ColumnMetadata col) {
        // buildColumnSql은 "good VARCHAR(255)" 같은 정의 부분을 리턴한다고 가정
        // [중요] IF NOT EXISTS 위치가 COLUMN 키워드 뒤에 옵니다.
        return "ALTER TABLE " + table.getTableName() +
                " ADD COLUMN IF NOT EXISTS " + buildColumnSql(col);
    }


}